### ISSUE TITLE
version 3.0 TODO

### ISSUE THREAD

**Issue by nswa17** [taulukointipalvelut/utab-core#11]
- [x] => motionはviewとの統合時?
- [x] tournamentでdb_urlは返さないほうがよい？
- [x] gsの終了条件
- [x] adjusted strictの方で,各DIVにconsiderとoutをつけてoutが0のところで分割して関数に放り込み、並列処理させてpromiseにする.
- [x] mongo_dump
- [x] function check_keys(necessary_keys, all_keys)
- [x] hasOwnProperty減らす
- [x] preev weightsをラウンドごとに設定する.(=>preev weightsはラウンドではなくジャッジ回数に依存)
- [x] 現時点でforce create未対応<=>名前の変更に未対応(名前を変えた人と同じ名前で新しく登録しようとするとエラー, create_hash外してDate.now()で代替すれば解決)
- [x] name long / short_nameどっちか
