### ISSUE TITLE
version 2.1 TODO

### ISSUE THREAD

**Issue by nswa17** [taulukointipalvelut/utab-core#14]
- [x] \*.\*.exists({name: "*"})の実装=>不要
- [x] dbのmetadataをどこに格納するか
- [x] dbchecksを分解
- [x] compileでrを指定しないと自動(他の部分も直せる)
- [x] team2ds揃ってないときにproceedroundするとどうなるか(unregistered)
- [x] shuffle venueしなくてもshuffleされる？
- [x] errorsインスタンスの仕様変更
- [x] institutions統合(schema, allocations, results, sys.find_one)
- [x] preevの重みづけ
- [x] chairに一人middle, panelにひとりhigh => 上の人から一人ずつ各squareにパネルを配置していく. 残りは通常の順で埋めていく(distribute_adjudicators)
- [x] summarize必要？compileで十分？
- [x] mongodbのmax connections, toomany open files
- [x] debater, institutionにはavailableは不要
- [x] loggerが動いていない.
- [x] /styles GET
- [x] throw an errorが機能していない.
- [x] check adj numでnumbersを受け取る.
- [x] measure slightness, allocate _to_slight
