### ISSUE TITLE
version 2.2 TODO

### ISSUE THREAD

**Issue by nswa17** [taulukointipalvelut/utab-core#15]
- [x] standardのフィルター改善
- [x] adjの数が偶数のときにwarning(chair0のときも)
- [x] 得たvote数, vote割合, 相手の勝ち点の平均(NAかつ１ラウンドなら相手の勝ち点に一致)
- [x] compile team results統合(integrate調整)
- [x] result送られてないのに1stラウンドでcompileされる
- [x] フォルダをignoreしない
- [x] team, adj, venue修正, warning修正(.available, .institutions, .priority, .debaters, .conflicts, .available)
- [x] new Error('details not defined')
- [x] checksを分割
