### ISSUE TITLE
version 2.0 TODO

### ISSUE THREAD

**Issue by nswa17** [taulukointipalvelut/utab-core#5]
- [x] allocationsの引数を使いやすく.
- [x] createの重複確認をidからnameに変更.
- [x] teams2debatersのcreate if existsを改善.
- [x] 文字列でmongodb url指定(mlab対応)
- [x] mongoose でoption がnewのとき, findOneできなかったらnullが返ってくるか+[unique index](https://docs.mongodb.com/v3.2/core/index-unique/), [q](http://stackoverflow.com/questions/14283503/unique-documents-using-multiple-values-in-mongoose-schema)
- [x] return promise改善
- [x] _idを返さない(紛らわしい)
- [x] errorはchecksで弾くようにする.
- [x] chairのかずに基づいたwarning
- [x] existか確認する
- [x] randomを参照透過に
- [x] hash付をする
- [x] logging
- [x] new Error    (object with .stringify())
- [x] vnでrandomか選択できるように
- [x] gsalg系でpanel配置
- [x] traditional系でallocate equally
- [x] refactor sortings
- [x] 自動allocationチェック
- [x] compare allocation改善(引数減らせる）
- [x] rollback(necessary?)
- [x] allocationsの保存は必要？（それをもとにresultsをチェックできる)
- [x] team_allocation のwudc
- [x] gs algorithmで複数チェア
- [x] exports改善(優先度低)
- [x] BP(adjchecksはchairのみ?)
- [x] one to many gale shapley, wudc standard matching
- [x] private variables(DB)
- [x] backup(=> view との統合時)
- [x] check results
- [x] allocation出す前のcheck(debaterがいるか)
- [x] userが好きに触れるdata領域(Schema定義+本体の変数名の変更)
- [x] chairの数が偶数のとき => ジャッジ間の相談で統一してもらう?
- [x] BPのranking => ジャッジ間で統一してもらう
